AllCops:
  Exclude:
    - 'Guardfile'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed

Style/DotPosition:
  EnforcedStyle: trailing

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "[]"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/Blocks:
  Exclude:
    - spec/**/*.rb

Style/EachWithObject:
  Enabled: false

Style/SignalException:
  Enabled: false
